default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: development
# development:
#   adapter: sqlite3
#   database: database.db
# test:
#   adapter: sqlite3
#   database: database.db
# production:
#   adapter: postgresql
#   database: sch_database mydb
